
language: java

jdk:
    - openjdk6
    - openjdk7
    - oraclejdk6
    - oraclejdk7

before_install:
    - curl -s get.gvmtool.net | bash
    - source "$HOME/.gvm/bin/gvm-init.sh"
    - gvm install grails 2.1.1
    - gvm use grails 2.1.1

script: grails test-app