
language: java

jdk:
    - openjdk6
    - openjdk7
    - oraclejdk6
    - oraclejdk7

before_install:
     - sudo add-apt-repository -y ppa:groovy-dev/grails
     - sudo apt-get update
     - sudo apt-get -y install grails-ppa
     - sudo apt-get install grails-2.1.1

script: grails test-app