
language: java

jdk:
    - openjdk6
    - openjdk7
    - oraclejdk6
    - oraclejdk7

branches:
  only:
    - master

before_script:
     - chmod +x grailsw
     - ./grailsw refresh-dependencies
     - ./grailsw compile

script: ./grailsw test-app